server:
  port: 9000
spring:
  application:
    name: service-getway
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
      - name: Hystrix
        args:
          name : default
          fallbackUri: 'forward:/defaultFallback'
      routes:
      - id: payment-router
        uri: lb://service-payment
        predicates:
        - Path=/pay/**